# These are supported funding model platforms

github: brtmvdl
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom: https://link.mercadopago.com.br/brtmvdl
